server:
  port: 8081

spring:
  application:
    name: account-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

data:
  mongodb:
    host: localhost
    port: 27017
    database: myapp

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms


    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 600000

  spring-doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest